# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: proto/ros2_logger.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.api.annotations_pb2
import proto.ros2_logger_pb2


class ROS2LoggerServiceBase(abc.ABC):

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
        }


class ROS2LoggerServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        pass
