# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ros_logger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/ros_logger.proto\x12\x1eviamlabs.service.ros_logger.v1\x1a\x1cgoogle/api/annotations.proto\":\n\nSumRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n\x07numbers\x18\x02 \x03(\x01R\x07numbers\"\x1f\n\x0bSumResponse\x12\x10\n\x03sum\x18\x01 \x01(\x01R\x03sum2\xae\x01\n\x10ROSLoggerService\x12\x99\x01\n\x03Sum\x12*.viamlabs.service.ros_logger.v1.SumRequest\x1a+.viamlabs.service.ros_logger.v1.SumResponse\"9\x82\xd3\xe4\x93\x02\x33\"1/viamlabs/api/v1/service/ros_logger/{name}/statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ros_logger_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROSLOGGERSERVICE.methods_by_name['Sum']._options = None
  _ROSLOGGERSERVICE.methods_by_name['Sum']._serialized_options = b'\202\323\344\223\0023\"1/viamlabs/api/v1/service/ros_logger/{name}/status'
  _globals['_SUMREQUEST']._serialized_start=88
  _globals['_SUMREQUEST']._serialized_end=146
  _globals['_SUMRESPONSE']._serialized_start=148
  _globals['_SUMRESPONSE']._serialized_end=179
  _globals['_ROSLOGGERSERVICE']._serialized_start=182
  _globals['_ROSLOGGERSERVICE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
