# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: proto/ros_logger.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.api.annotations_pb2
import proto.ros_logger_pb2


class ROSLoggerServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Sum(self, stream: 'grpclib.server.Stream[proto.ros_logger_pb2.SumRequest, proto.ros_logger_pb2.SumResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/viamlabs.service.ros_logger.v1.ROSLoggerService/Sum': grpclib.const.Handler(
                self.Sum,
                grpclib.const.Cardinality.UNARY_UNARY,
                proto.ros_logger_pb2.SumRequest,
                proto.ros_logger_pb2.SumResponse,
            ),
        }


class ROSLoggerServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Sum = grpclib.client.UnaryUnaryMethod(
            channel,
            '/viamlabs.service.ros_logger.v1.ROSLoggerService/Sum',
            proto.ros_logger_pb2.SumRequest,
            proto.ros_logger_pb2.SumResponse,
        )
